version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@SSWORD123
      POSTGRES_DB: productos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:P@SSWORD123@db:5432/productos
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
