//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeguridadSistemaEntities : DbContext
    {
        public SeguridadSistemaEntities()
            : base("name=SeguridadSistemaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auditoria> Auditorias { get; set; }
        public virtual DbSet<Sesione> Sesiones { get; set; }
        public virtual DbSet<TokensSeguridad> TokensSeguridads { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
