//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceBook
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Book : object
    {
        
        private string AuthorField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBook.IServiceBook")]
    public interface IServiceBook
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/GetBooks", ReplyAction="http://tempuri.org/IServiceBook/GetBooksResponse")]
        System.Threading.Tasks.Task<ServiceBook.Book[]> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/GetOneBook", ReplyAction="http://tempuri.org/IServiceBook/GetOneBookResponse")]
        System.Threading.Tasks.Task<ServiceBook.Book> GetOneBookAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/AddBook", ReplyAction="http://tempuri.org/IServiceBook/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(ServiceBook.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/UpdateBook", ReplyAction="http://tempuri.org/IServiceBook/UpdateBookResponse")]
        System.Threading.Tasks.Task UpdateBookAsync(ServiceBook.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBook/DeleteBook", ReplyAction="http://tempuri.org/IServiceBook/DeleteBookResponse")]
        System.Threading.Tasks.Task DeleteBookAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IServiceBookChannel : ServiceBook.IServiceBook, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ServiceBookClient : System.ServiceModel.ClientBase<ServiceBook.IServiceBook>, ServiceBook.IServiceBook
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceBookClient() : 
                base(ServiceBookClient.GetDefaultBinding(), ServiceBookClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceBook.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBookClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceBookClient.GetBindingForEndpoint(endpointConfiguration), ServiceBookClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBookClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceBookClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBookClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceBookClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBookClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceBook.Book[]> GetBooksAsync()
        {
            return base.Channel.GetBooksAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceBook.Book> GetOneBookAsync(int Id)
        {
            return base.Channel.GetOneBookAsync(Id);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(ServiceBook.Book book)
        {
            return base.Channel.AddBookAsync(book);
        }
        
        public System.Threading.Tasks.Task UpdateBookAsync(ServiceBook.Book book)
        {
            return base.Channel.UpdateBookAsync(book);
        }
        
        public System.Threading.Tasks.Task DeleteBookAsync(int Id)
        {
            return base.Channel.DeleteBookAsync(Id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceBook))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceBook))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50449/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceBookClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceBook);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceBookClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceBook);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceBook,
        }
    }
}
